services:
  mysql_adocao_pets:
    image: mysql:latest
    container_name: mysql_adocao_pets
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adocao_pets
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql